chore: use github actions
davidmarkclements/rfdc pull request #20
Opened 2020-11-25 14:18 UTC by salmanm

Noticed travis is stuck on https://github.com/davidmarkclements/rfdc/pull/19.

2020-12-17 09:40 UTC, simoneb approved these changes

2020-12-17 09:48 UTC, mcollina requested changes

2020-12-17 09:48 UTC, mcollina commented on .github/workflows/ci.yml
> +        node-version: [8.x, 10.x, 12.x]
```suggestion
        node-version: [8.x, 10.x, 12.x, 14.x]
```

2020-12-17 16:47 UTC, mcollina approved these changes
lgtm

2020-12-23 07:34 UTC, salmanm commented
@davidmarkclements could you take a look?

2020-12-23 07:36 UTC, simoneb approved these changes

2020-12-23 09:49 UTC, merged